AWSTemplateFormatVersion: 2010-09-09
Description: Este template crea instancias EC2 para los entornos dev, qa y prod

Parameters:
  Environment:
    Type: String
    Description: El entorno que se está creando

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-01234567890abcdef
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  InstanceIP:
    Value: !GetAtt EC2Instance.PublicIpAddress
